language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nosetests --verbosity=3 -x --with-coverage --cover-package=graph,osm,utils  --cover-html
