coverage:
  status:
    project:
      unit_integration:
        target: 10%
        threshold: 1%
        flag: unitintegration
    patch:
      unit_integration:
        target: 0%
        threshold: 0%
        flag: unitintegration%
