# Automatically generated by Pynguin.
import pytest
import utils.geo_tools as module0
import unittest


class IntegrationTest(unittest.TestCase):
    def test_case_0(self):
        var0 = 180.0
        var1 = 2118.01088
        var2 = 100.0
        var3 = module0.distance(var0, var1, var2, var1)
        assert var3 == pytest.approx(8898386.658367889, abs=0.01, rel=0.01)
