name: Build Status

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install networkx
        pip install black codecov flake8 mypy pytest pytest-cov
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=160 --statistics
    - name: Install and run Black
      run: black --check .
    - name: Typechecking with mypy
      run: mypy . --ignore-missing-imports
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml
        codecov
